name: Backup Routine
on:
  workflow_dispatch:
  schedule:
    # Runs at 04:00 UTC on the 1st and 17th of every month
    - cron: "0 4 1,15 * *"

jobs:
  backup-production-dataset:
    runs-on: ubuntu-latest
    name: Backup production dataset
    permissions:
      contents: read       # Needed for actions/checkout
      actions: write       # Needed for artifact upload
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn --prefer-offline --frozen-lockfile

      - name: Export production dataset
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_VIEWER_TOKEN }}
        run: |
          BACKUP_FILENAME="tilleggsstonader-brev-sanity-$(date +"%Y%m%d_%H%M%S").tar.gz"
          npx sanity dataset export production "backups/$BACKUP_FILENAME"
          echo "BACKUP_FILENAME=$BACKUP_FILENAME" >> "$GITHUB_ENV"

      - name: Verify backup file
        run: |
          if [ ! -f "backups/${{ env.BACKUP_FILENAME }}" ]; then
            echo "Backup file not created"
            exit 1
          fi

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Backup production dataset ${{ env.BACKUP_FILENAME }}
          path: backups/${{ env.BACKUP_FILENAME }}
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error

      - name: Post build failures to Slack
        if: failure()
        run: |
          curl -X POST --data "{\"text\": \"Backup av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}