name: Backup Routine
on:
  workflow_dispatch:
  schedule:
    # Runs at 04:00 UTC on the 1st and 17th of every month
    - cron: "0 4 1,15 * *"

jobs:
  backup-production-dataset:
    runs-on: ubuntu-latest
    name: Backup production dataset
    permissions:
      contents: read       # Needed for actions/checkout
      actions: write       # Needed for artifact upload
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn --prefer-offline --frozen-lockfile

      - name: Export production dataset
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_VIEWER_TOKEN }}
        run: |
          BACKUP_FILENAME="tilleggsstonader-brev-sanity-$(date +"%Y%m%d_%H%M%S").tar.gz"
          npx sanity dataset export production "backups/$BACKUP_FILENAME"
          echo "BACKUP_FILENAME=$BACKUP_FILENAME" >> "$GITHUB_ENV"

      - name: Verify backup file
        run: |
          if [ ! -f "backups/${{ env.BACKUP_FILENAME }}" ]; then
            echo "Backup file not created"
            exit 1
          fi

      - name: Upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Backup production dataset ${{ env.BACKUP_FILENAME }}
          path: backups/${{ env.BACKUP_FILENAME }}
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
