name: Build and deploy prod
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read       # Needed for actions/checkout
      actions: write       # Needed for artifact upload
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          cache: yarn
          cache-dependency-path: ./package.json
          node-version: 24

      - name: Installer sanity
        run: yarn global add sanity@latest && sanity install

      - name: Deploy sanity
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
        run: sanity deploy
